---
enabled_roles:
  - ranger
  - tmux
  - beets
  - ssh
  - sway
  - mpd
  - lazy_neovim
  - ideavim
  - vscode
  - mise
  - lazygit
  - docker
  - wezterm
  - waybar
  - fuzzel
  - vnc
  - hiddify
  - ohmyposh
  - foot
  - linux_setup
  - programs
  - wakatime
  - mako
  - zsh
  - bash
  - git
  - voxtype
