---
roles_to_exclude:
  # I'm not using Windows anymore (I had enough)
  - vscode
  - powershell
  - windows_setup
  - glazewm

  # I'm not using X anymore
  - i3
  - i3status
  - polybar
  - rofi
  - awesome

  # Foot is my choice now
  - alacritty
  - wezterm

  # Vanilla things I played with for fun
  - emacs
  - neovim

  # I'm afraid of it
  - doom

  # Not now
  - vifm  # lf better
  - fcitx # I'm not chinese
  - virtual
  - polybar
  - alacritty
  - oh-my-posh
  - lf
  - xplr
  - emacs
  - wezterm
  - swaylock
  - fcitx
  - latex


default_roles:
  - alacritty
  - polybar
  - oh-my-posh
  - wezterm
  - zsh
  - docker
  - ssh
  - lf
  - swaylock
  - xplr
  - emacs
  - mako
  - vnc
  - virtual
  - fuzzel
  - fcitx
  - sway
  - lazygit
  - ideavim
  - vscode
  - git
  - mpv
  - neovim
  - vifm
  - programs
  - windows_setup
  - powershell
  - lazy_neovim
  - gtk3
  - doom
  - rofi
  - glazewm
  - tmux
  - bash
  - awesome
  - mise
  - i3
  - firefox
  - hiddify
  - linux_setup
  - latex
  - waybar
  - foot
  - ranger
  - wakatime
  - i3status
