---
- name: Install snapd from AUR
  ansible.builtin.include_tasks: roles/common_tasks/tasks/require_aur_packages.yml
  vars:
    aur_packages:
      - snapd
    aur_requirement_context: snap role

- name: Unmask snapd service
  ansible.builtin.systemd:
    name: snapd.service
    masked: false
  become: true

- name: Enable and start snapd service
  ansible.builtin.systemd:
    name: snapd.service
    enabled: true
    state: started
  become: true

- name: Enable and start snapd apparmor unit
  ansible.builtin.systemd:
    name: snapd.apparmor
    enabled: true
    state: started
  become: true
