---
- name: Install niri packages from pacman
  community.general.pacman:
    name: "{{ pacman_item }}"
    state: present
  loop:
    - niri
    - xwayland-satellite
    - fuzzel
    - satty
    - jq
    - mako
    - slurp
    - waybar
    - btop
    - ttf-jetbrains-mono-nerd
    - qt6-wayland # Wayland support for Qt6
    - qt5-wayland # Wayland support for Qt5
    - wlsunset # warm screen display
    - xdg-desktop-portal
    - xdg-desktop-portal-wlr
    - xdg-desktop-portal-gtk
    - xdg-user-dirs
    - wf-recorder
    - polkit # authorization framework that lets unprivileged processes request permission from privileged system services
    - polkit-gnome # authentication agent for polkit
    - seahorse # GUI key and password manager
  loop_control:
    loop_var: pacman_item
  become: true
