---
- name: Find distro specific task file
  ansible.builtin.set_fact:
    distribution_task_file: "{{ lookup('ansible.builtin.first_found', distribution_task_params) }}"
  vars:
    distribution_task_params:
      files:
        - "{{ ansible_facts['distribution'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"
      paths:
        - "{{ role_path }}/tasks"
      skip: true

- name: Run distro specific tasks
  ansible.builtin.include_tasks: "{{ distribution_task_file }}"
  when: distribution_task_file | length > 0

- name: Ensure local icons directory exists for niri
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.local/share/icons"
    state: directory
    mode: "0755"
