---
- name: "Checking for distribution config"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: distribution_config

- name: "Run distro specific tasks"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: distribution_config.stat.exists

- name: Ensure local icons directory exists for niri
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.local/share/icons"
    state: directory
    mode: "0755"
