---
- name: Install fish shell and integrations
  community.general.pacman:
    name:
      - fish
      - starship
      - zoxide
      - fzf
      - eza
      - bat
      - ripgrep
      - fd
      - lazygit
      - fastfetch
      - atuin
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"

- name: Set fish as default shell
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    shell: /usr/bin/fish
  become: true
  when: ansible_facts['distribution'] == "Archlinux"
