---
- name: Install fish shell and integrations
  community.general.pacman:
    name:
      - fish
      - starship
      - zoxide
      - fzf
      - eza
      - bat
      - ripgrep
      - fd
      - lazygit
      - fastfetch
      - atuin
    state: present
  become: true
  when: ansible_facts['distribution'] == "Archlinux"
