---
- name: Install pacman packages
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/archlinux/packages.yml"
  when: ansible_facts['distribution'] == "Archlinux"

- name: Install AUR packages
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/archlinux/aur.yml"
  when: ansible_facts['distribution'] == "Archlinux"

- name: Install Flatpak applications
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/archlinux/flatpak.yml"
  when: ansible_facts['distribution'] == "Archlinux"

- name: Configure RTK
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/archlinux/rtk.yml"
  when: ansible_facts['distribution'] == "Archlinux"

- name: Configure Context7
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/archlinux/context7.yml"
  when: ansible_facts['distribution'] == "Archlinux"

- name: Install global agent skills
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/archlinux/skills.yml"
  when: ansible_facts['distribution'] == "Archlinux"
