---
- name: Install packages from pacman
  community.general.pacman:
    name: "{{ pacman_item }}"
    state: present
  loop:
    - ripgrep # better grep
    - zathura # pdf viewer
    - zip
    - unzip
    - eza # better ls
    - wget
    - tldr # better man pages
    - bat # better cat
    - trash-cli
    - zsh # better shell
    - mise # dev tools version manager
    - wlsunset # warm screen display
    - fzf # fuzzy searching tool
    - qbittorrent # torrent client
    - qt6-wayland
    - qt5-wayland
    - duf # better df
    - zoxide # better cd
    - lshw
    - vivaldi
    - telegram-desktop
    - nemo # file manager (found it better than thunder)
    - fastfetch # rip neofetch
    - blueman # bluetooth gui manager
    - btop # better htop/top
    - meld # gui diffing tool
    - gnome-keyring # keyring itself
    - libsecret # for keyring
    - seahorse # afair its for keyring
    # - lf # to much os specific configuration that doesn't make sense for me
    # - xplr # rust based lua hackable tui file manager, too complicated
    - ranger # terminal file manager
    - mpv # video player
    - jq # json processor
    - ark # kde gui archives manager
    - baobab # storage analyzer gui
    - ncdu # space analyzer
    - hyprpicker # Wayland color picker
    - caligula # dd wrapper with cool features
    - wl-clipboard # its and couple more down are the waybinder dependencies (look for the binary in the /bin + https://gitlab.com/cscs/waybinder)
    - wtype
    - zenity # gui gtk propmts
  become: true
  loop_control:
    loop_var: pacman_item
  when: ansible_distribution == "Archlinux"


# - name: Install packages from AUR
#   ansible.builtin.command: yay -S --noconfirm {{ aur_item }}
#   loop:
#     # - stretchly-bin # don't stare at screen too hard
#     - hiddify
#     # - zen-browser-bin # memory consumption is insane
#     - lazydocker-bin # docker TUI
#   loop_control:
#     loop_var: aur_item
#   when: ansible_distribution == "Archlinux"

- name: Setup dev globals
  ansible.builtin.command: mise use -g {{ mise_item }}@latest
  loop:
    - node
    - python
  loop_control:
    loop_var: mise_item
  when: ansible_distribution == "Archlinux"
