---
- name: Install packages from pacman
  community.general.pacman:
    name: "{{ pacman_item }}"
    state: present
  loop:
    - glab
    - base-devel
    - bun
    - git-lfs
    - xdg-desktop-portal-wlr
    - xdg-desktop-portal-gtk
    - github-cli
    - ripgrep # better grep
    # - zathura # pdf viewer
    - evince # pdf viewer
    - remind # proper reminder tool
    - zip
    - unzip
    - eza # better ls
    - wget
    - tldr # better man pages
    - bat # better cat
    - trash-cli
    - zsh # better shell
    - mise # dev tools version manager
    - wlsunset # warm screen display
    - wltype
    - fzf # fuzzy searching tool
    - qbittorrent # torrent client
    - qt6-wayland
    - qt5-wayland
    - duf # better df
    - zoxide # better cd
    - lshw
    - vivaldi
    - telegram-desktop
    - nemo # file manager (found it better than thunder)
    - fastfetch # rip neofetch
    - blueman # bluetooth gui manager
    - btop # better htop/top
    - meld # gui diffing tool
    - gnome-keyring # keyring itself
    - libsecret # for keyring
    - seahorse # afair its for keyring
    # - xplr # rust based lua hackable tui file manager, too complicated
    - mpv # video player
    - jq # json processor
    - yq # yaml, toml etc. processor
    - ark # kde gui archives manager
    - baobab # storage analyzer gui
    - ncdu # space analyzer
    - hyprpicker # Wayland color picker
    - caligula # dd wrapper with cool features
    - wl-clipboard # its and couple more down are the waybinder dependencies (look for the binary in the /bin + https://gitlab.com/cscs/waybinder)
    - wtype
    - tree
    - zenity # gui gtk propmts
    - eog # eye of gnome - image viewer
    - tesseract # OCR program
  become: true
  loop_control:
    loop_var: pacman_item
  when: ansible_distribution == "Archlinux"


- name: Install packages from AUR
  ansible.builtin.command: yay -S --noconfirm {{ aur_item }}
  loop:
    # - stretchly-bin # don't stare at screen too hard
    - zen-browser-bin
    - lazydocker-bin # docker TUI
    - throne-bin # docker TUI
    - voxtype-bin
  loop_control:
    loop_var: aur_item
  when: ansible_distribution == "Archlinux"

- name: Setup dev globals
  ansible.builtin.command: mise use -g {{ mise_item }}@latest
  loop:
    - node
  loop_control:
    loop_var: mise_item
  when: ansible_distribution == "Archlinux"

- name: Check if rtk is installed
  ansible.builtin.command: command -v rtk
  register: rtk_check
  changed_when: false
  failed_when: false
  when: ansible_distribution == "Archlinux"

- name: Install rtk
  ansible.builtin.shell: curl -fsSL https://raw.githubusercontent.com/rtk-ai/rtk/refs/heads/master/install.sh | sh
  args:
    executable: /bin/bash
  when:
    - ansible_distribution == "Archlinux"
    - rtk_check.rc != 0

- name: Enable rtk globally
  ansible.builtin.command: rtk init --global --auto-patch
  when: ansible_distribution == "Archlinux"

- name: Install bun tools
  ansible.builtin.command: bun i -g {{ bun_item }}
  loop:
    - "@steipete/summarize"
  loop_control:
    loop_var: bun_item
  when: ansible_distribution == "Archlinux"

- name: Install global skills
  ansible.builtin.command: bunx skills install {{ skill_item }} -y --all -g
  loop:
    - "vercel-labs/skills --skill find-skills"
    - "anthropics/skills --skill skill-creator"
    - "anthropics/skills --skill frontend-design"
    - "vercel-labs/agent-skills --skill web-design-guidelines"
    - "vercel-labs/agent-skills --skill vercel-react-best-practices"
    - "affaan-m/everything-claude-code --skill frontend-patterns"
    - "affaan-m/everything-claude-code --skill docker-patterns"
    - "openclaw/openclaw --skill gh-issues"
    - "openclaw/openclaw --skill github"
    - "github/awesome-copilot --skill git-commit"
    - "openai/skills --skill gh-fix-ci"
    - "Shubhamsaboo/awesome-llm-apps --skill code-reviewer"
    - "affaan-m/everything-claude-code --skill coding-standards"
    - "affaan-m/everything-claude-code --skill api-design"
    - "langgenius/dify --skill backend-code-review"
    - "anthropics/skills --skill algorithmic-art"
    - "affaan-m/everything-claude-code --skill java-coding-standards"
    - "affaan-m/everything-claude-code --skill jpa-patterns"
    - "affaan-m/everything-claude-code --skill springboot-patterns"
    - "affaan-m/everything-claude-code --skill springboot-security"
    - "marcelorodrigo/agent-skills --skill spring-boot-testing"
    - "affaan-m/everything-claude-code --skill database-migrations"
    - "affaan-m/everything-claude-code --skill postgres-patterns"
    - "affaan-m/everything-claude-code --skill python-patterns"
    - "affaan-m/everything-claude-code --skill python-testing"
    - "Shubhamsaboo/awesome-llm-apps --skill python-expert"
    - "Shubhamsaboo/awesome-llm-apps --skill visualization-expert"
    - "browser-use/browser-use --skill browser-use"
    - "vercel-labs/agent-browser --skill agent-browser"
    - "michalparkola/tapestry-skills-for-claude-code --skill article-extractor"
    - "Shubhamsaboo/awesome-llm-apps --skill decision-helper"
    - "Shubhamsaboo/awesome-llm-apps --skill editor"
    - "Shubhamsaboo/awesome-llm-apps --skill technical-writer"
    - "Shubhamsaboo/awesome-llm-apps --skill email-drafter"
    - "Shubhamsaboo/awesome-llm-apps --skill meeting-notes"
    - "Shubhamsaboo/awesome-llm-apps --skill sprint-planner"
    - "Shubhamsaboo/awesome-llm-apps --skill strategy-advisor"
    - "blader/humanizer --skill humanizer"
  loop_control:
    loop_var: skill_item
  when: ansible_distribution == "Archlinux"
