---
- name: Set OS-specific config paths for Windows
  ansible.builtin.set_fact:
    config_path: "{{ ansible_user_profile }}"
  when: ansible_os_family == 'Windows'

- name: Include common copy tasks
  ansible.builtin.include_tasks: roles/common_tasks/tasks/copy_configs.yml
