FROM fedora:41

HEALTHCHECK NONE

RUN useradd -d /home/username -m -s /bin/bash username
USER username

ENV ANSIBLE_CONFIG=/home/username/.ansible.cfg

RUN dnf install -y \
    ansible-2.17.5 \
    python3-pip-22.0.2 \
    git-2.34.1 && \
    dnf clean all

WORKDIR /home/dotfiles

COPY . .

ENTRYPOINT ["ansible-playbook", "main.yml", "-i", "localhost,"]
