FROM ubuntu:22.04

HEALTHCHECK NONE

RUN useradd -d /home/username -m -s /bin/bash username
USER username

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    ansible=2.17.5 \
    python3-pip=22.0.2 \
    git=2.34.1 --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /home/dotfiles

COPY . .

ENTRYPOINT ["ansible-playbook", "main.yml", "-i", "localhost,"]