---
- name: Configure dotfiles and system settings
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - /vars/sensitive_vars.yml
    - /vars/configuration.yml

  # pre_tasks:

  #   - name: Include Windows pre-tasks
  #     ansible.builtin.include_tasks: pre_tasks/windows.yml
  #     when: ansible_os_family == 'Windows'

  #   - name: Include Linux pre-tasks
  #     ansible.builtin.include_tasks: pre_tasks/linux.yml
  #     when: ansible_distribution == 'Ubuntu'

  tasks:
    - name: set roles
      set_fact:
        roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
      tags:
        - always
                  
    - name: Display roles
      debug: "var=roles"
      tags:
        - always

    - name: Display os
      debug: "var=ansible_os_family"
      tags:
        - always

    - name: Run roles
      include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ roles }}"
      tags:
        - always
