---
- name: Configure dotfiles and system settings
  hosts: localhost
  connection: local
  gather_facts: true

  pre_tasks:
    - name: Include Windows pre-tasks
      ansible.builtin.include_tasks: pre_tasks/windows.yml
      when: ansible_os_family == 'Windows'

    - name: Include Ubuntu pre-tasks
      ansible.builtin.include_tasks: pre_tasks/Ubuntu.yml
      when: ansible_distribution == 'Ubuntu'

    - name: Include Fedora pre-tasks
      ansible.builtin.include_tasks: pre_tasks/Fedora.yml
      when: ansible_distribution == 'Fedora'

    - name: Include Fedora pre-tasks
      ansible.builtin.include_tasks: pre_tasks/Archlinux.yml
      when: ansible_distribution == 'Archlinux'

  tasks:
    - name: Display distribution
      debug: "var=ansible_distribution"
      tags:
        - always

    - name: set roles_to_run
      set_fact:
        roles_to_run: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(roles_to_exclude | default([])) }}"
      tags:
        - always
    
    - name: Display roles
      debug: "var=roles_to_run"
      tags:
        - always

    # In case I'll need to have the same vars in many places in the future
    # roles/sensitive_vars/tasks/main.yml
    # - name: Load sensitive variables
    #   ansible.builtin.include_vars:
    #   file: /vars/sensitive_vars.yml

    - name: Run roles
      # include_role:
      #   name: sensitive_vars
      include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ roles_to_run }}"
      tags:
        - always
