---
- name: Configure dotfiles and system settings
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - /vars/sensitive_vars.yml

  pre_tasks:
    - name: Include Windows pre-tasks
      ansible.builtin.include_tasks: pre_tasks/windows.yml
      when: ansible_os_family == 'Windows'

    - name: Include Linux pre-tasks
      ansible.builtin.include_tasks: pre_tasks/linux.yml
      when: ansible_os_family == 'Linux'

  tasks:
    - name: Set combined roles fact
      ansible.builtin.set_fact:
        combined_roles: "{{ (group_vars.all.roles | default([])) + (group_vars[ansible_os_family | lower].roles | default([])) }}"

  roles:
    - role: "{{ item }}"
      when: item in combined_roles
      loop: "{{ combined_roles }}"
