---
- name: "Remove lazy"
  file:
    path: "{{ ansible_user_dir }}/.local/share/nvim/lazy"
    state: absent

- name: "Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true
  when: ansible_distribution == 'Archlinux'
