---
- name: Install required packages on Fedora
  ansible.builtin.dnf:
    name: "{{ dnf_item }}"
    state: present
  loop:
    - curl
    - ripgrep
    - fd-find
    - gcc
  become: true
  loop_control:
    loop_var: dnf_item
  when: ansible_distribution == "Fedora"

- name: "Create config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory
  when: ansible_distribution == 'Fedora'

- name: "Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true
  when: ansible_distribution == 'Fedora'
