---
- name: Install Neovim and its dependencies on Windows using Scoop
  community.windows.win_scoop:
    name: "{{ item }}"
    state: present
  loop:
    - neovim
    - curl
    - gcc
    - vcredist2022
    - ripgrep
  when: ansible_os_family == 'Windows'

# - name: Set OS-specific config paths
#   ansible.builtin.set_fact:
#     config_path: "{{ ansible_user_dir }}/.config/nvim"

# - name: Remove Neovim configuration directories
#   ansible.builtin.file:
#     path: "{{ item }}"
#     state: absent
#   loop:
#     - "{{ config_path }}"
#     - "{{ ansible_user_dir }}/.local/share/nvim"
#   when: ansible_distribution == 'Ubuntu'

# - name: Include common copy tasks
#   ansible.builtin.include_tasks: roles/common_tasks/tasks/copy_configs.yml