---
- name: Ensure .config directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/lazygit"
    state: directory
    mode: "0755"

- name: Create a symlink to a file
  file:
    src: "{{ role_path }}/files/config.yml"
    dest: "{{ ansible_user_dir }}/.config/lazygit/config.yml"
    state: link
