---
- name: Install packages from pacman
  community.general.pacman:
    name: "{{ pacman_item }}"
    state: present
  loop:
    - lazygit
  become: true
  loop_control:
    loop_var: pacman_item
  when: ansible_facts['distribution'] == "Archlinux"

- name: Ensure .config directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/lazygit"
    state: directory
    mode: "0755"

- name: Create a symlink to a file
  ansible.builtin.file:
    src: "{{ role_path }}/files/config.yml"
    dest: "{{ ansible_facts['user_dir'] }}/.config/lazygit/config.yml"
    state: link
    force: true
