---
- name: Set OS-specific config paths for Windows
  ansible.builtin.set_fact:
    config_path: "{{ ansible_user_profile }}\\.config\\lazygit"
  when: ansible_os_family == 'Windows'

- name: Install Lazygit on Windows using Scoop
  community.windows.win_scoop:
    name: lazygit
    state: present
  when: ansible_os_family == 'Windows'

- name: Include common copy tasks
  ansible.builtin.include_tasks: roles/common_tasks/tasks/copy_configs.yml