---
- name: Install packages from pacman
  community.general.pacman:
    name: "{{ pacman_item }}"
    state: present
  loop:
    - blueman
    - bluez
    - bluez-utils
  become: true
  loop_control:
    loop_var: pacman_item
  when: ansible_facts['distribution'] == "Archlinux"

- name: Ensure bluetooth service is enabled and running
  ansible.builtin.systemd_service:
    name: bluetooth
    enabled: true
    state: started
  become: true
