---
- name: Install vifm on Linux
  ansible.builtin.apt:
    name: vifm
    state: present
    update_cache: true
  become: true
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Install vifm on Windows using Scoop
  community.windows.win_scoop:
    name: vifm
    state: present
  when: ansible_facts['os_family'] == 'Windows'
