---
- name: Install FCITX 5
  ansible.builtin.apt:
    name: fcitx5
    state: present
  become: true

- name: Install FCITX input methods
  ansible.builtin.apt:
    name: fcitx5-*
    state: present
  become: true

- name: Configure FCITX profile
  ansible.builtin.template:
    src: profile
    dest: "{{ ansible_facts['user_dir'] }}/.config/fcitx5"
    mode: '0644'
  become: true

- name: Enable FCITX
  ansible.builtin.service:
    name: fcitx
    enabled: true
    state: started
  become: true
