---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - fontconfig
      - wget
    state: present
  become: true
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Include common linux bash setup
  ansible.builtin.include_tasks: roles/linux_setup/tasks/linux.yml
