---
- name: Create font directory
  file:
    path: /usr/local/share/fonts
    state: directory
    mode: '0755'
  become: yes

- name: Download JetBrains Mono Nerd Font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip
    dest: /tmp/JetBrainsMono.zip
  become: yes

- name: Unzip JetBrains Mono Nerd Font
  unarchive:
    src: /tmp/JetBrainsMono.zip
    dest: /usr/local/share/fonts/
    remote_src: yes
  become: yes

- name: Update font cache
  command: fc-cache -f -v
  become: yes

- name: Clean up downloaded font zip
  file:
    path: /tmp/JetBrainsMono.zip
    state: absent
  become: yes
