---
- name: Create font directory
  ansible.builtin.file:
    path: /usr/local/share/fonts
    state: directory
    mode: '0755'
  become: true

- name: Download JetBrains Mono Nerd Font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip
    dest: /tmp/JetBrainsMono.zip
  become: true

- name: Unzip JetBrains Mono Nerd Font
  unarchive:
    src: /tmp/JetBrainsMono.zip
    dest: /usr/local/share/fonts/
    remote_src: true
  become: true

- name: Update font cache
  command: fc-cache -f -v
  become: true

- name: Clean up downloaded font zip
  ansible.builtin.file:
    path: /tmp/JetBrainsMono.zip
    state: absent
  become: true

- name: Add user to commonly used groups
  user:
    name: "{{ ansible_user_id }}"
    groups: "sudo, libvirt, sound, video, docker, plugdev, lpadmin, netdev, input, tty, users, i2c, spi, gpio"
    append: true
  become: true
