---
- name: "{{ role_name }} | Set Windows dark theme"
  win_regedit:
    path: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize
    name: AppsUseLightTheme
    data: 0
    type: dword

- name: "{{ role_name }} | Copy custom cursor files"
  win_copy:
    src: files/cursor/
    dest: '%USERPROFILE%\\cursors'

- name: "{{ role_name }} | Install custom cursor"
  win_shell: |
    rundll32.exe desk.cpl,InstallScreenSaver {{ cursor_inf_path }}

- name: "{{ role_name }} | Configure wallpaper slideshow"
  win_regedit:
    path: HKCU:\Control Panel\Desktop
    name: Wallpaper
    data: files/wallpapers
