---
- name: Create a symlink
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/lf"
    state: link
    force: true

- name: Check if a command exists
  ansible.builtin.command: which stpv
  register: stpv_check
  ignore_errors: true

- name: Set fact if command exists
  ansible.builtin.set_fact:
    stpv_exists: true
  when: stpv_check.rc == 0

- name: Set fact if command does not exist
  ansible.builtin.set_fact:
    stpv_exists: false
  when: stpv_check.rc != 0

- name: Clone the Git repository
  ansible.builtin.git:
    repo: https://github.com/Naheel-Azawy/stpv.git
    dest: /tmp/stpv
    update: false
  when: not stpv_exists

- name: Install the package using make
  ansible.builtin.command: make install
  args:
    chdir: /tmp/stpv
  become: true
  when: not stpv_exists

- name: Remove the cloned directory
  ansible.builtin.file:
    path: /tmp/stpv
    state: absent
  when: not stpv_exists

- name: Ensure lf.bash executable
  ansible.builtin.file:
    path: "{{ role_path }}/files/lf.bash"
    state: file
    mode: '0755'
