---
- name: Enable project Test of the user schlupov
  community.general.copr:
    state: enabled
    name: pennbauman/ports
  become: true

- name: Ensure lf is installed
  dnf:
    name: lf
    state: present
  become: true

- name: Set OS-specific config paths
  ansible.builtin.set_fact:
    config_path: "{{ ansible_user_dir }}/.config/lf"

- name: Include common copy tasks
  ansible.builtin.include_tasks: roles/common_tasks/tasks/copy_configs.yml
