# roles/alacritty/molecule/default/molecule.yml
---
dependency:
  name: galaxy
  options:
    requirements-file: ../../../../requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_user: root
verifier:
  name: ansible
