---
- name: Set OS-specific config paths
  ansible.builtin.set_fact:
    config_path: "{{ ansible_facts['user_dir'] }}/.ssh"

- name: Include common copy tasks
  ansible.builtin.include_tasks: roles/common_tasks/tasks/copy_configs.yml

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ config_path }}"
    state: directory
    mode: '0700'

- name: Find copied SSH files
  ansible.builtin.find:
    paths: "{{ config_path }}"
    recurse: false
    hidden: true
    file_type: file
  register: ssh_files

- name: Set permissions for all public keys
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: file
    mode: '0644'
  loop: "{{ ssh_files.files }}"
  when: item.path.endswith('.pub')

- name: Set permissions for all private keys
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: file
    mode: '0600'
  loop: "{{ ssh_files.files }}"
  when: not item.path.endswith('.pub')
