---
- name: Check for chezmoi on Linux
  ansible.builtin.command:
    cmd: chezmoi --version
  register: chezmoi_check
  changed_when: false
  failed_when: false
  when: ansible_facts['os_family'] != 'Windows'

- name: Install chezmoi on Linux
  ansible.builtin.package:
    name: chezmoi
    state: present
  become: true
  when:
    - ansible_facts['os_family'] != 'Windows'
    - chezmoi_check.rc != 0

- name: Install chezmoi on Windows
  community.windows.win_scoop:
    name: chezmoi
    state: present
  when: ansible_facts['os_family'] == 'Windows'

- name: Sync chezmoi source on Linux
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}/chezmoi/"
    dest: "{{ ansible_facts['user_dir'] }}/.local/share/dotfiles-chezmoi/"
    archive: true
    delete: true
  when: ansible_facts['os_family'] != 'Windows'

- name: Ensure chezmoi config directory exists on Linux
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/chezmoi"
    state: directory
    mode: "0700"
  when: ansible_facts['os_family'] != 'Windows'

- name: Install chezmoi age identity on Linux
  ansible.builtin.copy:
    src: age-key.txt
    dest: "{{ ansible_facts['user_dir'] }}/.config/chezmoi/key.txt"
    mode: "0600"
  no_log: true
  diff: false
  when: ansible_facts['os_family'] != 'Windows'

- name: Initialize chezmoi config on Linux
  ansible.builtin.command:
    cmd: >-
      chezmoi init
      --source "{{ ansible_facts['user_dir'] }}/.local/share/dotfiles-chezmoi"
      --force
      --no-tty
  changed_when: true
  when: ansible_facts['os_family'] != 'Windows'

- name: Apply chezmoi source on Linux
  ansible.builtin.command:
    cmd: >-
      chezmoi apply
      --source "{{ ansible_facts['user_dir'] }}/.local/share/dotfiles-chezmoi"
      --force
      --no-tty
  changed_when: true
  no_log: true
  when: ansible_facts['os_family'] != 'Windows'

- name: Apply chezmoi source on Windows
  ansible.windows.win_command: >-
    chezmoi apply
    --source "{{ playbook_dir }}\\chezmoi"
    --force
    --no-tty
  changed_when: true
  no_log: true
  when: ansible_facts['os_family'] == 'Windows'
