---
- name: Install packages from pacman
  community.general.pacman:
    name: "{{ pacman_item }}"
    state: present
  loop:
    - zsh
    - eza # better ls
    - wget # better curl
    - tldr # better man pages
    - bat # better cat
    - fzf # fuzzy finder
    - fd # better find
    - atuin # magical shell history
    - zoxide # better cd
    - ripgrep # better grep
    - ttf-nerd-fonts-symbols-mono
  become: true
  loop_control:
    loop_var: pacman_item

- name: Set Zsh as the default shell
  ansible.builtin.user:
    name: "{{ ansible_facts['env']['USER'] }}"
    shell: /usr/bin/zsh
  become: true
