---
- name: Install Zsh
  pacman:
    name: zsh
    state: present
  become: true

- name: Set Zsh as the default shell
  user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/zsh
  become: true

- name: Install Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh


- name: Clone zsh-syntax-highlighting repository
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ lookup('env', 'ZSH_CUSTOM') | default('~/.oh-my-zsh/custom') }}/plugins/zsh-syntax-highlighting"
    update: yes
  become: true

- name: Remove default .zshrc configuration
  file:
    path: ~/.zshrc
    state: absent

- name: Create a symbolic link for .zshrc
  file:
    src: ~/dotfiles/roles/zsh/files/.zshrc
    dest: ~/.zshrc
    state: link

- name: Create a symbolic link for .aliases
  file:
    src: ~/dotfiles/roles/zsh/files/.aliases
    dest: ~/.aliases
    state: link
