---
- name: Delete a directory
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/mise"
    state: absent
  when: ansible_facts['distribution'] == 'Archlinux'

- name: "Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_facts['user_dir'] }}/.config/mise"
    state: link
    force: true
  when: ansible_facts['distribution'] == 'Archlinux'
