---
- name: Install zed from pacman
  community.general.pacman:
    name: zed
    state: present
  become: true

- name: Create zed config symlink
  ansible.builtin.include_tasks: roles/common_tasks/tasks/create_symlinks.yml
  vars:
    symlink:
      src: "{{ role_path }}/files"
      dest: "{{ ansible_facts['user_dir'] }}/.config/zed"
      remove_existing: true
