---
- name: Install theme packages from pacman
  community.general.pacman:
    name: "{{ pacman_item }}"
    state: present
  loop:
    - kvantum
    - kvantum-qt5
    - qt5ct # configuration utility for Qt5 apps
    # - qt6ct # configuration utility for Qt6 apps
  loop_control:
    loop_var: pacman_item
  become: true

- name: Delete GTK config directories before recreating symlinks
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/{{ gtk_config_dir }}"
    state: absent
  loop:
    - gtk-3.0
    - gtk-4.0
  loop_control:
    loop_var: gtk_config_dir
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Create symlinks to role files directory for GTK configs
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_facts['user_dir'] }}/.config/{{ gtk_config_dir }}"
    state: link
    force: true
  loop:
    - gtk-3.0
    - gtk-4.0
  loop_control:
    loop_var: gtk_config_dir
  when: ansible_facts['distribution'] == 'Archlinux'
