---
- name: Install theme packages from pacman
  community.general.pacman:
    name: "{{ pacman_item }}"
    state: present
  loop:
    - kvantum
    - kvantum-qt5
    - qt5ct # configuration utility for Qt5 apps
    # - qt6ct # configuration utility for Qt6 apps
  loop_control:
    loop_var: pacman_item
  become: true
