# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
#
mouse_hide_wait -3.0
tab_bar_style powerline
tab_powerline_style round
shell /usr/bin/zsh
notify_on_cmd_finish invisible 20


# BEGIN_KITTY_THEME
# 3024 Night
include current-theme.conf
# END_KITTY_THEME

# BEGIN KITTY CURSOR

cursor_trail 200
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

# END KITTY CURSOR


background_tint         0.7
background_tint_gaps    -10.0

window_border_width     1pt
active_border_color     #44ffff
single_window_margin_width 0
hide_window_decorations titlebar-only

# TODO
# allow_remote_control yes
# session
