---
- name: Install Git on Linux
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: true
  become: true
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
    - ansible_facts['pkg_mgr'] == 'apt'
