---
- name: Converge
  hosts: all
  tasks:
    - name: Update package cache
      ansible.builtin.raw: pacman -Syu --noconfirm
      changed_when: true

    - name: Install Python for Ansible
      ansible.builtin.raw: pacman -S --noconfirm python
      changed_when: true

    - name: Include tmux role
      ansible.builtin.include_role:
        name: tmux
