---
- name: Install Flatpak package
  community.general.pacman:
    name: flatpak
    state: present
  become: true

- name: Add Flathub repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  become: true

- name: Install Gear Lever from Flathub
  community.general.flatpak:
    name: it.mijorus.gearlever
    state: present
    remote: flathub
  become: true

- name: Install applications from Flathub
  community.general.flatpak:
    name: "{{ flatpak_app }}"
    state: present
    remote: flathub
  loop:
    - md.obsidian.Obsidian
    - io.github.anil_e.Codd
    - io.gitlab.theevilskeleton.Upscaler
  loop_control:
    loop_var: flatpak_app
  become: true
