---
- name: Install Powershell on Windows using Scoop
  community.windows.win_scoop:
    name: pwsh
    state: present
  when: ansible_facts['os_family'] == 'Windows'

- name: Install PowerShell modules
  ansible.windows.win_shell: |
    Install-Module -Name PSReadLine -Scope CurrentUser -Force
    Install-Module -Name Terminal-Icons -Scope CurrentUser -Force
    Install-Module -Name PSFzf -Scope CurrentUser -Force
    Install-Module -Name Recycle -Scope CurrentUser -Force
  args:
    executable: pwsh.exe
  when: ansible_facts['os_family'] == 'Windows'
