---
- name: Install Powershell on Windows using Scoop
  community.windows.win_scoop:
    name: pwsh
    state: present
  when: ansible_os_family == 'Windows'

- name: Install PowerShell modules
  ansible.windows.win_shell: |
    Install-Module -Name PSReadLine -Scope CurrentUser -Force
    Install-Module -Name Terminal-Icons -Scope CurrentUser -Force
    Install-Module -Name PSFzf -Scope CurrentUser -Force
    Install-Module -Name Recycle -Scope CurrentUser -Force
  args:
    executable: pwsh.exe
  when: ansible_os_family == 'Windows'


- name: Create PowerShell config directories
  ansible.windows.win_file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ansible_user_profile }}\\Documents\\PowerShell"
    - "{{ ansible_user_profile }}\\.config\\powershell"
  when: ansible_os_family == 'Windows'


- name: Create main PowerShell profile
  ansible.windows.win_copy:
    content: . $env:USERPROFILE\.config\powershell\profile.ps1
    dest: "{{ ansible_user_profile }}\\Documents\\PowerShell\\Microsoft.PowerShell_profile.ps1"
  when: ansible_os_family == 'Windows'


- name: Create actual PowerShell config
  ansible.windows.win_copy:
    src: profile.ps1
    dest: "{{ ansible_user_profile }}\\.config\\powershell\\profile.ps1"
  when: ansible_os_family == 'Windows'
