---
- name: Install dependencies for Linux
  package:
    name: "{{ item }}"
    state: present
  loop:
    - neovim
    - python3-neovim
    - git
    - curl
    - ripgrep  # Optional
    - fd      # Optional, better file finder
  when: ansible_os_family == "Debian"

- name: Install Neovim using package manager for non-Debian Linux
  package:
    name: neovim
    state: present
  when: ansible_os_family != "Debian"

- name: Create Neovim configuration directory
  file:
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: Copy init.vim configuration
  template:
    src: init.vim.j2
    dest: "{{ ansible_user_dir }}/.config/nvim/init.vim"

- name: Install vim-plug (plugin manager for Neovim)
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_user_dir }}/.local/share/nvim/site/autoload/plug.vim"
    mode: '0755'

- name: Ensure Neovim plugins are installed
  command: nvim +PlugInstall +qall