---
- name: Install packages
  dnf:
    name: rofimoji
    state: present
  become: true
  when: ansible_distribution == 'Fedora'

- name: Set Bash config path
  ansible.builtin.set_fact:
    config_path: "{{ ansible_user_dir }}/.config/rofi"

- name: Copy Bash config files
  ansible.builtin.include_tasks: roles/common_tasks/tasks/copy_configs.yml

