---
- name: Install packages
  dnf:
    name: rofimoji
    state: present
  become: true
  when: ansible_distribution == 'Fedora'

- name: "Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/rofi"
    state: link
    force: true
  when: ansible_distribution == 'Fedora'

- name: Ensure off.sh executable
  file:
    path: ~/.config/rofi/off.sh
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

