---
- name: Install packages from pacman
  community.general.pacman:
    name: "{{ pacman_item }}"
    state: present
  loop:
    - mpd
    - mpc
    - ncmpcpp
  become: true
  loop_control:
    loop_var: pacman_item
  when: ansible_distribution == "Archlinux"

- name: Ensure .mpd directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.mpd"
    state: directory
    mode: "0755"

- name: Create a symlink to a file
  ansible.builtin.file:
    src: "{{ role_path }}/files/mpd.conf"
    dest: "{{ ansible_user_dir }}/.mpd/mpd.conf"
    state: link
    force: true
