---
- name: Install packages from pacman
  community.general.pacman:
    name: "{{ pacman_item }}"
    state: present
  loop:
    - tmux
  become: true
  loop_control:
    loop_var: pacman_item
  when: ansible_distribution == "Archlinux"

- name: Create a symlink to a file
  ansible.builtin.file:
    src: "{{ role_path }}/files/.tmux.conf"
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    state: link
    force: true