---
- name: Set Bash config path
  ansible.builtin.set_fact:
    config_path: "{{ ansible_user_dir }}"

- name: Copy Bash config files
  ansible.builtin.include_tasks: roles/common_tasks/tasks/copy_configs.yml

