---
- name: Delete a directory
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/waybar"
    state: absent

- name: "Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/endeavour_waybar"
    dest: "{{ ansible_facts['user_dir'] }}/.config/waybar"
    state: link
    force: true
  when: ansible_facts['distribution'] == 'Archlinux'
