---
- name: Delete a directory
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/foot"
    state: absent

- name: Create a symlink to a file
  ansible.builtin.file:
    src: "{{ role_path }}/files/"
    dest: "{{ ansible_facts['user_dir'] }}/.config/foot"
    state: link
    force: true
