---
- name: Install packages from pacman
  community.general.pacman:
    name: "{{ pacman_item }}"
    state: present
  loop:
    - docker
    - docker-compose
  become: true
  loop_control:
    loop_var: pacman_item
  when: ansible_facts['distribution'] == "Archlinux"

- name: Reload systemd manager configuration
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Create docker group
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: Add user volard to docker group
  ansible.builtin.user:
    name: volard
    groups: docker
    append: true
  become: true

- name: Enable and start Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
