---
- name: Install Docker packages
  ansible.builtin.dnf:
    name:
      - docker-cli
      - containerd
      - docker-compose
    state: present
  become: true
  when:
    - ansible_distribution == 'Fedora'
