---
- name: Find distro specific task file
  ansible.builtin.set_fact:
    distribution_task_file: "{{ lookup('ansible.builtin.first_found', distribution_task_params) }}"
  vars:
    distribution_task_params:
      files:
        - "{{ ansible_facts['distribution'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"
      paths:
        - "{{ role_path }}/tasks"
      skip: true

- name: Run distro specific tasks
  ansible.builtin.include_tasks: "{{ distribution_task_file }}"
  when: distribution_task_file | length > 0

# I live in garbage country

- name: Ensure .config directory exists
  ansible.builtin.file:
    path: "/etc/docker"
    state: directory
    mode: "0755"
  become: true

- name: "Check for config"
  ansible.builtin.copy:
    src: daemon.json
    dest: "/etc/docker/daemon.json"
    mode: "0644"
  become: true

- name: "Restart docker"
  ansible.builtin.systemd:
    name: docker
    state: restarted
  become: true
