---

- name: Delete a directory
  file:
    path: "{{ ansible_user_dir }}/.config/sway"
    state: absent

- name: "Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/endeavour_sway"
    dest: "{{ ansible_user_dir }}/.config/sway"
    state: link
    force: true
  when: ansible_distribution == 'Archlinux'