---
# https://forum.endeavouros.com/t/unable-to-share-screen-with-sway-wm/46654
- name: Install packages from pacman
  community.general.pacman:
    name: "{{ pacman_item }}"
    state: present
  loop:
    - xdg-desktop-portal-wlr
    - xdg-desktop-portal
    - pipewire
    - waybar
  become: true
  loop_control:
    loop_var: pacman_item
  when: ansible_facts['distribution'] == "Archlinux"

# - name: Enable and start pipewire service
#   ansible.builtin.systemd:
#     name: pipewire
#     enabled: true
#     state: started
#   when: ansible_facts['distribution'] == 'Archlinux'
#
# - name: Enable and start pipewire service
#   ansible.builtin.systemd:
#     name: xdg-desktop-portal
#     enabled: true
#     state: started
#   when: ansible_facts['distribution'] == 'Archlinux'

# reload the system

- name: Install greetd sway config
  ansible.builtin.copy:
    src: "{{ role_path }}/greetd/greetd-sway.cfg"
    dest: /etc/greetd/sway.cfg
    owner: root
    group: root
    mode: "0644"
  become: true
