---
- name: Install required packages on Fedora
  ansible.builtin.dnf:
    name: "{{ dnf_item }}"
    state: present
  loop:
    - sway
    - sweet-gtk-theme
    - swayidle
  become: true
  loop_control:
    loop_var: dnf_item
  when: ansible_facts['distribution'] == "Fedora"
