---
- name: Install required packages on Fedora
  ansible.builtin.dnf:
    name: "{{ dnf_item }}"
    state: present
  loop:
    - sway
    - sweet-gtk-theme
  become: true
  loop_control:
    loop_var: dnf_item
  when: ansible_distribution == "Fedora"


- name: Set OS-specific config paths
  ansible.builtin.set_fact:
    config_path: "{{ ansible_user_dir }}/.config/sway"

- name: Include common copy tasks
  ansible.builtin.include_tasks: roles/common_tasks/tasks/copy_configs.yml

- name: Ensure the script is executable
  file:
    path: "{{ ansible_user_dir }}/.config/sway/dynamic_wallpapers.sh"
    mode: '0755'          # Set the permissions to make it executable
  become: true
