---
- name: Install required packages on Linux
  ansible.builtin.apt:
    name: "{{ apt_item }}"
    state: present
  loop:
    - sway
    - light
    - waybar
    - alsa-utils
    - mpc
    - nitrogen
    - rofi
  become: true
  loop_control:
    loop_var: apt_item
  when: ansible_facts['os_family'] in ["Debian", "Ubuntu"]


- name: Include common copy tasks
  ansible.builtin.include_tasks: roles/rofi/tasks/main.yml
