---
- name: Check if .bashrc exists
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.bashrc"
  register: bashrc_stat

- name: Create .bashrc if it doesn't exist
  ansible.builtin.copy:
    content: source $HOME/.config/.termrc
    dest: "{{ ansible_user_dir }}/.bashrc"
    mode: "0644"
  when:
    - not bashrc_stat.stat.exists

- name: Check if source line already exists
  ansible.builtin.command: grep -Fxq "PATH=$PATH:$HOME/dotfiles/bin" "{{ ansible_user_dir }}/.bashrc"
  register: grep_result
  changed_when: false
  failed_when: false
  when:
    - bashrc_stat.stat.exists

- name: Add source line to existing .bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: PATH=$PATH:$HOME/dotfiles/bin
    state: present
  when:
    - bashrc_stat.stat.exists
    - grep_result.rc != 0 # Only add line if grep didn't find it

- name: Source bashrc for the current shell session
  block:
    - name: Check if running interactively
      set_fact:
        is_interactive: "{{ lookup('env', 'PS1') is defined }}"
      changed_when: false

    - name: Source bashrc if interactive
      when: is_interactive
      command: /bin/bash -c "source ~/.bashrc"
      changed_when: false
  become: no
