---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: full
    autoclean: true
    autoremove: true
  become: true
  when: ansible_distribution == 'Ubuntu'
