---
- name: Copy Ansible-managed encrypted SSH config files
  when: role_name == 'ssh'
  block:
    - name: Ensure config directory exists
      ansible.builtin.file:
        path: "{{ config_path }}"
        state: directory
        mode: "0700"

    - name: Find SSH configuration files
      ansible.builtin.find:
        paths: "{{ role_path }}/files"
        recurse: false
        hidden: true
        file_type: file
      register: config_files

    - name: Copy SSH files
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: "{{ config_path }}/{{ item.path | basename }}"
        mode: preserve
      loop: "{{ config_files.files }}"
      no_log: true

- name: Skip role-managed config copies
  ansible.builtin.debug:
    msg: "User config files are managed by chezmoi now."
  when: role_name != 'ssh'
