---
- name: Install packages from pacman
  community.general.community.general.pacman:
    name: "{{ pacman_item }}"
    state: present
  loop:
    - texlive-binextra # for latexmk
    - texlive-luatex # for lualatex
    - texlive-latex # some tools and format files
  become: true
  loop_control:
    loop_var: pacman_item
  when: ansible_distribution == "Archlinux"

- name: "Create link to config for latexmk"
  ansible.builtin.file:
    src: "{{ role_path }}/files/.latexmkrc"
    dest: "{{ ansible_user_dir }}/.latexmkrc"
    state: link
    force: true
  become: true
