---
# - name: Install packages from pacman
#   pacman:
#     name: "{{ pacman_item }}"
#     state: present
#   loop:
#     - arc-gtk-theme
#   become: true
#   loop_control:
#     loop_var: pacman_item
#   when: ansible_distribution == "Archlinux"

- name: Delete a directory
  file:
    path: "{{ ansible_user_dir }}/.config/gtk-3.0"
    state: absent

- name: "Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/gtk-3.0"
    state: link
    force: true
  when: ansible_distribution == 'Archlinux'