---
- name: Delete a directory
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/fuzzel"
    state: absent

- name: Create a symlink to a file
  ansible.builtin.file:
    src: "{{ role_path }}/endeavour_fuzzel"
    dest: "{{ ansible_facts['user_dir'] }}/.config/fuzzel"
    state: link
    force: true

- name: Ensure bemoji directory exists
  ansible.builtin.file:
    path: /tmp/bemoji
    state: directory
    mode: "0755"

- name: Clone or update the bemoji repository
  ansible.builtin.git:
    repo: https://github.com/marty-oehme/bemoji.git
    dest: /tmp/bemoji
    update: true

- name: Make the bemoji script executable
  ansible.builtin.file:
    path: /tmp/bemoji/bemoji
    mode: '0755'
  become: true

- name: Move bemoji to /usr/local/bin
  ansible.builtin.command: mv /tmp/bemoji/bemoji /usr/local/bin/bemoji
  args:
    removes: /usr/local/bin/bemoji
  become: true

- name: Remove the bemoji directory
  ansible.builtin.file:
    path: /tmp/bemoji
    state: absent
