---
- name: Create local bin directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory
    mode: "0755"
  when: ansible_os_family == 'Windows'


- name: Install oh-my-posh on Windows
  community.windows.win_scoop:
    name: oh-my-posh
    state: present
  when: ansible_os_family == 'Windows'

- name: Set OS-specific config paths
  ansible.builtin.set_fact:
    config_path: "{{ ansible_user_dir }}/.config/oh-my-posh"

- name: Include common copy tasks
  ansible.builtin.include_tasks: roles/common_tasks/tasks/copy_configs.yml
