---
- name: "Install dependencies for Linux"
  package:
    name: "{{ item }}"
    state: present
  loop:
    - neovim
    - python3-neovim
    - git
    - curl
    - ripgrep
    - fd
  when: ansible_os_family == "Linux"

- name: "Create Neovim configuration directory"
  file:
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: "Copy configuration"
  template:
    src: init.vim.j2
    dest: "{{ ansible_user_dir }}/.config/nvim/init.vim"