---
name: Ansible CI
permissions: read-all
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - name: Install ansible-lint
        run: pip install ansible-lint
      - name: Install Galaxy Modules
        run: ansible-galaxy install -r requirements/common.yml
      - name: Linting with ansible-lint
        run: ansible-lint main.yml
