---
- name: Install packages from pacman
  community.general.pacman:
    name: "{{ pacman_item }}"
    state: present
  loop:
    - mako
  become: true
  loop_control:
    loop_var: pacman_item
  when: ansible_facts['distribution'] == "Archlinux"

- name: Create mako symlink
  ansible.builtin.include_tasks: roles/common_tasks/tasks/create_symlinks.yml
  vars:
    symlink:
      src: "{{ role_path }}/files"
      dest: "{{ ansible_facts['user_dir'] }}/.config/mako"
      remove_existing: true
  when: ansible_facts['distribution'] == 'Archlinux'
