---
- name: Install packages from pacman
  community.general.pacman:
    name: "{{ pacman_item }}"
    state: present
  loop:
    - mako
  become: true
  loop_control:
    loop_var: pacman_item
  when: ansible_facts['distribution'] == "Archlinux"

- name: Delete a directory
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/mako"
    state: absent

- name: "Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_facts['user_dir'] }}/.config/mako"
    state: link
    force: true
  when: ansible_facts['distribution'] == 'Archlinux'
